services:
  - type: web
    name: my-app
    runtime: python
    repo: https://github.com/nikaprrr312-glitch/fillwords
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app